###############################################################################################
# kms
# docker-compose build
# docker-compose up -d
###############################################################################################

FROM python:3.6-buster AS kms_ker

ENV TORCH_HOME /knowledge-management-system

WORKDIR ${TORCH_HOME}

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY apps/ker/requirements.txt apps/ker/
RUN pip3 install -r apps/ker/requirements.txt

COPY apps/ker_ko/requirements.txt apps/ker_ko/
RUN pip3 install -r apps/ker_ko/requirements.txt

RUN python -m nltk.downloader stopwords punkt wordnet
RUN python -m spacy download en

# install jdk to run mecab jar
RUN apt-get update
RUN apt-get install -y default-jre

# Korean tokenizer(mecab.jar) uses 8080 port , used by classifier
EXPOSE 8082

CMD ["bash", "./runserver.sh"]

