"""
Django settings for interface project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from neomodel import config
from config.config_manager import ConfigManager
import os

neo4j_dashboard_enabled = False

config_manager = ConfigManager()
if config_manager.get('neo4j_dashboard', 'enabled') == '1':
    neo4j_dashboard_enabled = True

if neo4j_dashboard_enabled:
    NEOADMIN_HOME = '/neo4j_dashboard/'

    # Neo4j DB Access Information
    neo4j_protocol = config_manager.get('neo4j_db', 'protocol')
    neo4j_uri = config_manager.get('neo4j_db', 'uri')
    neo4j_port = config_manager.get('neo4j_db', 'port')
    neo4j_username = config_manager.get('neo4j_db', 'username')
    neo4j_password = config_manager.get('neo4j_db', 'password')
    neo4j_db = f'{neo4j_uri}:{neo4j_port}'

    config.DATABASE_URL = f'{neo4j_protocol}://{neo4j_username}:{neo4j_password}@{neo4j_db}'
    config.ENCRYPTED_CONNECTION = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=tvqp+6jt&cl0pl1xu%p#!i1j7f(e=n$1i%yycn72=oyby74$)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['3.34.165.201', '10.178.133.132', '127.0.0.1']
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_api',
    'elasticapm.contrib.django',
]
if neo4j_dashboard_enabled:
    INSTALLED_APPS += ('neo4j_dashboard',)

ELASTIC_APM_SERIVCE_NAME = 'aiefw_'+config_manager.app_name

ELASTIC_APM = {
    'DEBUG': True,
    # Set required service name. Allowed characters:
    # a-z, A-Z, 0-9, -, _, and space
    'SERVICE_NAME': ELASTIC_APM_SERIVCE_NAME,

    # Use if APM Server requires a token
    'SECRET_TOKEN': 'qAguhBFvE6iOsExEq5',

    # Set custom APM Server URL (default: http://localhost:8200)
    'SERVER_URL': 'https://195a157051c7459a976b5687ee6592f7.apm.ap-northeast-2.aws.elastic-cloud.com:443',
}
LOGFILE = 'log/'+ELASTIC_APM_SERIVCE_NAME+'.log'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)8s] [%(elasticapm_trace_id)s] [%(name)s:%(lineno)d] %(funcName)s() : %(message)s'
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': BASE_DIR / LOGFILE,
            'backupCount': 10,
            'formatter': 'standard',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
    }
}

MIDDLEWARE = [
    'rest_api.middleware.CorsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
#    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'interface.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'interface.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL =  '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

app_name = config_manager.app_name
if app_name == "ker":
    STATICFILES_DIRS = [
            os.path.join(BASE_DIR, 'apps', 'ker', 'knowledge_extraction', 'server', 'image_db'),
    ]
elif app_name == "ker_ko":
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'apps', 'ker_ko', 'knowledge_extraction', 'server', 'image_db'),
    ]

MEDIA_URL =  '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


# Disabling the check for maximum bytes uploaded by POST
DATA_UPLOAD_MAX_MEMORY_SIZE = None
CORS_ALLOW_ALL_ORIGINS = True # If this is used then `CORS_ALLOWED_ORIGINS` will not have any effect
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGIN_REGEXES = [
    'http://localhost:8089',
]
